### ISSUE TITLE
How to disable the captcha field? RuntimeError: Model class captcha.models.CaptchaStore doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS when 'captcha' not in INSTALLED_APPS

### ISSUE THREAD

**Issue by macolo** [divio/aldryn-forms#168]
There is a check for 'ImportError', but django throws a `RuntimeError` instead which is not caught and causes the project to crash.

Workaround: Leave 'captcha' in INSTALLED_APPs and then unregister the plugin, but thats not a great solution.

https://github.com/aldryn/aldryn-forms/blob/master/aldryn_forms/cms_plugins.py#L854

```
  File "/Users/mario/.virtualenvs/djangocms-template/lib/python3.6/site-packages/captcha/fields.py", line 4, in <module>
    from captcha.models import CaptchaStore
  File "/Users/mario/.virtualenvs/djangocms-template/lib/python3.6/site-packages/captcha/models.py", line 25, in <module>
    class CaptchaStore(models.Model):
  File "/Users/mario/.virtualenvs/djangocms-template/lib/python3.6/site-packages/django/db/models/base.py", line 118, in __new__
    "INSTALLED_APPS." % (module, name)
RuntimeError: Model class captcha.models.CaptchaStore doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.
```

**Comment by victor-yunenko** [comment]
Indeed, basically the page becomes unusable, and this can happen at any point on the production server, once somebody decides to add a captcha field.

**Comment by victor-yunenko** [comment]
Hm, ok, actually I had another issue, similar but not the same, I raised it as #192

**Comment by victor-yunenko** [comment]
I'm assuming that issue isn't actual anymore since the captcha package is optional. Please feel free to reopen if the issue persists 👌
