### ISSUE TITLE
Google Recaptcha v3??

### ISSUE THREAD

**Issue by magnoliasoco** [divio/aldryn-forms#187]
I can't find this anywhere and appreciate any assistance. 

I have installed Aldryn Forms. It looks like it is using Django Simple Captcha. Does anyone have this working with Google's Recaptcha and what would be involved in doing so?  I appreciate your help and assistance.

**Comment by victor-yunenko** [comment]
It's definitely easily implementable, and I remember doing it ~4 times for different versions of aldryn-forms over the last year. I wish I had the time to add a PR for that in order to avoid doing it over and over again :)

**Comment by macolo** [comment]
Here is a first version. Feel free to contribute. 

https://gitlab.com/what-digital/aldryn-forms-recaptcha-plugin/

Alas, https://github.com/divio/aldryn-forms/issues/146 needs to be implemented before this can work out of the box.

**Comment by victor-yunenko** [comment]
https://gitlab.com/what-digital/aldryn-forms-recaptcha-plugin/ was lately updated for support of v3 invisible captcha and used in several production envirovments. I'm assuming I can close this ticket now - please feel free to reach out if needed.
