### ISSUE TITLE
Django 2.2 compatibility?

### ISSUE THREAD

**Issue by pinksharpii** [divio/aldryn-forms#191]
I see in setup.py that Django 2.2 is not explicitly listed as being compatible with this plugin. Is there a plan to make this so? We are running into an error with trying to spin up my local environment with aldryn_forms in the INSTALLED_APPS list.

`django.template.library.InvalidTemplateLibrary: Invalid template library specified. ImportError raised when trying to load 'aldryn_forms.templatetags.aldryn_forms_tags': cannot import name 'mark_safe' from 'django.utils.text' (/Users/kayla/dev/client/rebuild/venv/lib/python3.7/site-packages/django/utils/text.py)`

Is there a recommended solution to get past this?

**Comment by thidop** [comment]
I try using 'from django.utils.html import mark_safe' instead of 'from django.utils.text import mark_safe' and it seems to work.

**Comment by victor-yunenko** [comment]
Resolved in 5.0.0, although haven't deployed to pypi yet.

**Comment by jonathan-s** [comment]
Yes, also chiming in on wanting version 5 released on pypi.

**Comment by victor-yunenko** [comment]
Hi @FinalAngel, would you be able to push 5.0.1 to pypi or maybe provide me with the access on victor@what.digital :) ?

**Comment by victor-yunenko** [comment]
For the context - I've been running 5.0.1 on few projects for ~2 month now, one has already been pushed live at the beginning of January.

**Comment by FinalAngel** [comment]
@victor-yunenko can the current master be pushed?

**Comment by victor-yunenko** [comment]
@yvladislav, could you answer that? I think you pushed a fix for something on the last week?

**Comment by jonathan-s** [comment]
@FinalAngel @victor-yunenko To answer your question, I would say that is a yes. Considering that the fix that @yvladislav pushed is a simple autoescape in emails (https://github.com/divio/aldryn-forms/commit/a731bc2727cd53712a08a3441291ddf0a3447a25) I think it's safe to say that current master can be pushed.

**Comment by victor-yunenko** [comment]
@FinalAngel , yes would be amazing if you could push it :)

**Comment by mamiyak** [comment]
When can I install version 5.0.3 from pypi? I'm waiting for that...

**Comment by arjan-s** [comment]
Please, can anyone push 5.x to to PyPI? I'm also eagerly waiting for my last dependency on Django 1.x to move on to Django 2.x or even 3.x.
Thanks!

**Comment by PolitiDisclose** [comment]
@FinalAngel @jonathan-s Any chance we can get this on PyPi? I have a project waiting on this as well.

**Comment by FinalAngel** [comment]
@PolitiDisclose 5.0.4 is now uploaded to pypi :)
