### ISSUE TITLE
wrong import of "mark_save" inside aldryn_forms_tags.py

### ISSUE THREAD

**Issue by Qadosch** [divio/aldryn-forms#195]
`from django.utils.text import mark_safe`
https://github.com/divio/aldryn-forms/blob/master/aldryn_forms/templatetags/aldryn_forms_tags.py

based on djangos github mark_save is inside savestring seems like an error based on django 2.1.x to 2.2.x update
https://github.com/django/django/blob/master/django/utils/safestring.py

getting this error on divio project deploy after installing forms update:
django.template.library.InvalidTemplateLibrary: Invalid template library specified. ImportError raised when trying to load 'aldryn_forms.templatetags.aldryn_forms_tags': cannot import name 'mark_safe'
[0m

**Comment by macolo** [comment]
@Qadosch aldryn-forms is not yet compatible with django >2. Try django 1.11

**Comment by Qadosch** [comment]
I figured that.
I cannot use django 1.11 since i am using divio cloud and their automatisms and dont want to care about compatibilities.
Looks like an small fuckup of @FinalAngel or @vThaian 
I recomend changing
`from django.utils.text import mark_safe`
to
`from django.utils.savestring import mark_safe`

**Comment by macolo** [comment]
@Qadosch hm it appears you are right and divio cloud sets up django 2.2 by default

![image](https://user-images.githubusercontent.com/4056979/68999589-b6b1ba80-08c2-11ea-84a1-2254a4d6d1ac.png)

You can however try to downgrade your aldryn-django addon to 1.11 in the versions tab.

But indeed aldryn forms should be compatible with django 2.2 🤔

**Comment by macolo** [comment]
There is a merge request here that should be merged: https://github.com/divio/aldryn-forms/pull/194

**Comment by macolo** [comment]
cc @victor-yunenko

**Comment by victor-yunenko** [comment]
I saw this problem. It’s possible to downgrade on divio to 2.1 by downgrading aldryn-addons, that’s what I’ve done. 

The MR works as well.

**Comment by victor-yunenko** [comment]
We've received access to the repository and now can resolve it. I expect the fix to be released in a week.

For now I'll close it in favor of an older issue #191 and the #188.

**Comment by didierCH** [comment]
> from django.utils.savestring import mark_safe

except that it must be 

`from django.utils.safestring import mark_safe`

it works.
