### ISSUE TITLE
on aldryn the captcha field causes an error

### ISSUE THREAD

**Issue by stefanfoulis** [divio/aldryn-forms#32]
this is because django-simple-captcha requires the captcha urls to be included.

Simple workaround: add the captcha urls to the apphook.

Clean fix: needs the aldryn platform to support custom url inclusions (without apphooks).

**Comment by czpython** [comment]
@stefanfoulis on apphooks is a bit messy to do this.. specially if you want multiple form with captchas, what do you think about using the ```get_plugin_urls()``` on the cms plugin class?

The downside of this is that by default this sets the urls under /admin so it exposes /admin path.
The upside is that it's much easier and requires less hack, plus user does not have to use apphook.

**Comment by victor-yunenko** [comment]
Agreed, I'll close it in favor of removing this captcha from the requirements in #146

And the readme should be extended as well.
